import "dotenv/config";

const PORT = process.env.PORT;
const DB_HOST = process.env.DB_HOST;
const DB_USERNAME = process.env.DB_USERNAME;
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_DIALECT = process.env.DB_DIALECT;
const DB_PORT = process.env.DB_PORT;
const DB_NAME = process.env.DB_NAME;
const PEM_PATH = process.env.PEM_PATH;
const ENV = process.env.ENV;
const {
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_CERT_URI,
  FIREBASE_CLIENT_URL,
  FIREBASE_UNIVER_DOMAIN,
  JWT_TOKEN,
} = process.env;

const envVars = {
  PORT,
  DB_DIALECT,
  DB_HOST,
  DB_NAME,
  DB_PASSWORD,
  DB_PORT,
  DB_USERNAME,
  PEM_PATH,
  ENV,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI,
  FIREBASE_CERT_URI,
  FIREBASE_CLIENT_URL,
  FIREBASE_UNIVER_DOMAIN,
  JWT_TOKEN,
};

export default envVars;
