services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
