services:
  app:
    build: .
    network_mode: "host"
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    network_mode: "host"
